# Generated by Django 4.1.1 on 2022-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
