# Generated by Django 4.1.1 on 2022-09-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='read_time_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
