# Generated by Django 4.1.1 on 2022-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_description_post_body_post_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
