# Generated by Django 4.1 on 2022-09-29 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_email_post_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 10, 36, 36, 281059, tzinfo=datetime.timezone.utc)),
        ),
    ]
