# Generated by Django 4.1 on 2022-09-29 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author_post_author_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload_image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 11, 57, 54, 208473, tzinfo=datetime.timezone.utc)),
        ),
    ]
