# Generated by Django 4.1 on 2022-09-29 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_article_photo_alter_post_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 12, 14, 2, 1024, tzinfo=datetime.timezone.utc)),
        ),
    ]
