# Generated by Django 4.1.1 on 2022-09-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('reading_time', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('author_name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=100)),
                ('claps', models.IntegerField()),
            ],
        ),
    ]
