# Generated by Django 4.1.1 on 2022-10-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writer", models.CharField(max_length=15)),
                ("writer_email", models.EmailField(max_length=100)),
                ("claps", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("written_time", models.DateTimeField(auto_now_add=True)),
                ("reading_time", models.IntegerField(default=1)),
            ],
            options={"ordering": ["written_time"],},
        ),
    ]
