# Generated by Django 4.1.1 on 2022-10-01 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="post",
            name="author_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="post", name="claps_count", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="description_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="post",
            name="posted_date",
            field=models.DateField(default=datetime.date(2022, 10, 1)),
        ),
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="post",
            name="response_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
