# Generated by Django 4.1.1 on 2022-10-01 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_author_email_post_author_name_post_claps_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="posted_date",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 10, 1, 13, 33, 12, 267783, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
