# Generated by Django 4.1.1 on 2022-10-01 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_posted_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="posted_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
