# Generated by Django 4.1.1 on 2022-09-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('tags', models.JSONField()),
                ('author_email', models.EmailField(max_length=254)),
                ('content_format', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('canonical_url', models.URLField()),
                ('public_status', models.CharField(max_length=10)),
                ('notify_followers', models.BooleanField()),
            ],
        ),
    ]
