# Generated by Django 4.1.1 on 2022-10-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('writer', models.CharField(default='admin', max_length=100)),
                ('contents', models.TextField()),
                ('read_time', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
