# Generated by Django 4.1.1 on 2022-09-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author_mail', models.EmailField(max_length=100)),
            ],
        ),
    ]
