# Generated by Django 4.1.1 on 2022-09-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_image',
            field=models.URLField(blank=True),
        ),
    ]
