# Generated by Django 4.1.1 on 2022-09-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('publisher_name', models.CharField(max_length=50)),
                ('publisher_email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('images', models.FileField(upload_to='')),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
