# Generated by Django 4.1.1 on 2022-09-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_mail',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
