# Generated by Django 4.1.1 on 2022-09-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_author_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_mail',
            field=models.EmailField(max_length=300),
        ),
    ]
