# Generated by Django 4.0 on 2022-09-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffleblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
    ]
