# Generated by Django 4.1.1 on 2022-10-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mainText', models.TextField(max_length=200)),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('userName', models.CharField(default='', max_length=200)),
                ('userMail', models.EmailField(max_length=254)),
            ],
        ),
    ]
