# Generated by Django 4.1.1 on 2022-10-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_title_post_heading_alter_post_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='heading',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='subheading',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
